### ISSUE TITLE
dependencies in list(dict) doesn't work

### ISSUE THREAD

**Issue by ignatenkobrain** [nicolaiarocci/cerberus#234]
```yaml
components:
  type: list
  required: True
  schema:
    type: dict
    schema:
      name:
        type: string
        required: True
      patches:
        type: string
        allowed:
          - keep
          - drop
      keep-patches:
        type: list
        dependencies:
          patches: drop
        schema:
          type: string
```

If `keep-patches` specified I want to ensure that `patches` is set to `drop`.

```yaml
components:
  - name: libsolv
    patches: drop
    keep-patches:
      - foo.patch
```
